export  class UserGitData {

usergit = [ {
                   "login": "mojombo",
                   "id": 1,
                   "node_id": "MDQ6VXNlcjE=",
                   "avatar_url": "https://avatars0.githubusercontent.com/u/1?v=4",
                   "gravatar_id": "",
                   "url": "https://api.github.com/users/mojombo",
                   "html_url": "https://github.com/mojombo",
                   "followers_url": "https://api.github.com/users/mojombo/followers",
                   "following_url": "https://api.github.com/users/mojombo/following{/other_user}",
                   "gists_url": "https://api.github.com/users/mojombo/gists{/gist_id}",
                   "starred_url": "https://api.github.com/users/mojombo/starred{/owner}{/repo}",
                   "subscriptions_url": "https://api.github.com/users/mojombo/subscriptions",
                   "organizations_url": "https://api.github.com/users/mojombo/orgs",
                   "repos_url": "https://api.github.com/users/mojombo/repos",
                   "events_url": "https://api.github.com/users/mojombo/events{/privacy}",
                   "received_events_url": "https://api.github.com/users/mojombo/received_events",
                   "type": "User",
                   "site_admin": false,
                   "name": "Tom Preston-Werner",
                   "company": null,
                   "blog": "http://tom.preston-werner.com",
                   "location": "San Francisco",
                   "email": null,
                   "hireable": null,
                   "bio": null,
                   "public_repos": 61,
                   "public_gists": 62,
                   "followers": 21501,
                   "following": 11,
                   "created_at": "2007-10-20T05:24:19Z",
                   "updated_at": "2019-05-15T16:51:02Z"
               },
               {
                   "login": "brunokoga",
                   "id": 1219990,
                   "node_id": "MDQ6VXNlcjEyMTk5OTA=",
                   "avatar_url": "https://avatars1.githubusercontent.com/u/1219990?v=4",
                   "gravatar_id": "",
                   "url": "https://api.github.com/users/brunokoga",
                   "html_url": "https://github.com/brunokoga",
                   "followers_url": "https://api.github.com/users/brunokoga/followers",
                   "following_url": "https://api.github.com/users/brunokoga/following{/other_user}",
                   "gists_url": "https://api.github.com/users/brunokoga/gists{/gist_id}",
                   "starred_url": "https://api.github.com/users/brunokoga/starred{/owner}{/repo}",
                   "subscriptions_url": "https://api.github.com/users/brunokoga/subscriptions",
                   "organizations_url": "https://api.github.com/users/brunokoga/orgs",
                   "repos_url": "https://api.github.com/users/brunokoga/repos",
                   "events_url": "https://api.github.com/users/brunokoga/events{/privacy}",
                   "received_events_url": "https://api.github.com/users/brunokoga/received_events",
                   "type": "User",
                   "site_admin": false,
                   "name": "Bruno Koga",
                   "company": "Appsterdam",
                   "blog": "http://www.brunokoga.com",
                   "location": null,
                   "email": null,
                   "hireable": null,
                   "bio": null,
                   "public_repos": 45,
                   "public_gists": 10,
                   "followers": 78,
                   "following": 39,
                   "created_at": "2011-11-25T11:30:02Z",
                   "updated_at": "2019-02-17T16:34:30Z"
               },
               {
                   "login": "brunoborges",
                   "id": 129743,
                   "node_id": "MDQ6VXNlcjEyOTc0Mw==",
                   "avatar_url": "https://avatars0.githubusercontent.com/u/129743?v=4",
                   "gravatar_id": "",
                   "url": "https://api.github.com/users/brunoborges",
                   "html_url": "https://github.com/brunoborges",
                   "followers_url": "https://api.github.com/users/brunoborges/followers",
                   "following_url": "https://api.github.com/users/brunoborges/following{/other_user}",
                   "gists_url": "https://api.github.com/users/brunoborges/gists{/gist_id}",
                   "starred_url": "https://api.github.com/users/brunoborges/starred{/owner}{/repo}",
                   "subscriptions_url": "https://api.github.com/users/brunoborges/subscriptions",
                   "organizations_url": "https://api.github.com/users/brunoborges/orgs",
                   "repos_url": "https://api.github.com/users/brunoborges/repos",
                   "events_url": "https://api.github.com/users/brunoborges/events{/privacy}",
                   "received_events_url": "https://api.github.com/users/brunoborges/received_events",
                   "type": "User",
                   "site_admin": false,
                   "name": "Bruno Borges",
                   "company": "@Microsoft",
                   "blog": "http://brunoborges.io",
                   "location": "Vancouver, Canada",
                   "email": null,
                   "hireable": null,
                   "bio": "Brazilian, Developer Relations and Engagement Strategist. Promoting great developer technologies to the world.",
                   "public_repos": 105,
                   "public_gists": 82,
                   "followers": 486,
                   "following": 59,
                   "created_at": "2009-09-22T01:06:33Z",
                   "updated_at": "2019-05-11T02:51:32Z"
                 },
                 {
                   "login": "brunophilipe",
                   "id": 2136642,
                   "node_id": "MDQ6VXNlcjIxMzY2NDI=",
                   "avatar_url": "https://avatars2.githubusercontent.com/u/2136642?v=4",
                   "gravatar_id": "",
                   "url": "https://api.github.com/users/brunophilipe",
                   "html_url": "https://github.com/brunophilipe",
                   "followers_url": "https://api.github.com/users/brunophilipe/followers",
                   "following_url": "https://api.github.com/users/brunophilipe/following{/other_user}",
                   "gists_url": "https://api.github.com/users/brunophilipe/gists{/gist_id}",
                   "starred_url": "https://api.github.com/users/brunophilipe/starred{/owner}{/repo}",
                   "subscriptions_url": "https://api.github.com/users/brunophilipe/subscriptions",
                   "organizations_url": "https://api.github.com/users/brunophilipe/orgs",
                   "repos_url": "https://api.github.com/users/brunophilipe/repos",
                   "events_url": "https://api.github.com/users/brunophilipe/events{/privacy}",
                   "received_events_url": "https://api.github.com/users/brunophilipe/received_events",
                   "type": "User",
                   "site_admin": false,
                   "name": "Bruno Philipe",
                   "company": "@blinkist",
                   "blog": "https://bruno.ph",
                   "location": "Berlin, Germany",
                   "email": null,
                   "hireable": null,
                   "bio": "I build software, mostly on iOS and macOS. I've created Kodex for iOS, Cakebrew and Noto for macOS, among other things.",
                   "public_repos": 88,
                   "public_gists": 5,
                   "followers": 229,
                   "following": 22,
                   "created_at": "2012-08-11T19:41:17Z",
                   "updated_at": "2019-05-26T23:44:23Z"
                 },
                 {
                   "login": "brunosimon",
                   "id": 5439991,
                   "node_id": "MDQ6VXNlcjU0Mzk5OTE=",
                   "avatar_url": "https://avatars2.githubusercontent.com/u/5439991?v=4",
                   "gravatar_id": "",
                   "url": "https://api.github.com/users/brunosimon",
                   "html_url": "https://github.com/brunosimon",
                   "followers_url": "https://api.github.com/users/brunosimon/followers",
                   "following_url": "https://api.github.com/users/brunosimon/following{/other_user}",
                   "gists_url": "https://api.github.com/users/brunosimon/gists{/gist_id}",
                   "starred_url": "https://api.github.com/users/brunosimon/starred{/owner}{/repo}",
                   "subscriptions_url": "https://api.github.com/users/brunosimon/subscriptions",
                   "organizations_url": "https://api.github.com/users/brunosimon/orgs",
                   "repos_url": "https://api.github.com/users/brunosimon/repos",
                   "events_url": "https://api.github.com/users/brunosimon/events{/privacy}",
                   "received_events_url": "https://api.github.com/users/brunosimon/received_events",
                   "type": "User",
                   "site_admin": false,
                   "name": "Bruno Simon",
                   "company": "@immersive-garden ",
                   "blog": "http://bruno-simon.ninja",
                   "location": "Paris",
                   "email": null,
                   "hireable": true,
                   "bio": null,
                   "public_repos": 37,
                   "public_gists": 1,
                   "followers": 179,
                   "following": 0,
                   "created_at": "2013-09-11T23:44:41Z",
                   "updated_at": "2019-03-27T09:01:36Z"
                 },
                 {
                   "login": "brunokrebs",
                   "id": 15347252,
                   "node_id": "MDQ6VXNlcjE1MzQ3MjUy",
                   "avatar_url": "https://avatars1.githubusercontent.com/u/15347252?v=4",
                   "gravatar_id": "",
                   "url": "https://api.github.com/users/brunokrebs",
                   "html_url": "https://github.com/brunokrebs",
                   "followers_url": "https://api.github.com/users/brunokrebs/followers",
                   "following_url": "https://api.github.com/users/brunokrebs/following{/other_user}",
                   "gists_url": "https://api.github.com/users/brunokrebs/gists{/gist_id}",
                   "starred_url": "https://api.github.com/users/brunokrebs/starred{/owner}{/repo}",
                   "subscriptions_url": "https://api.github.com/users/brunokrebs/subscriptions",
                   "organizations_url": "https://api.github.com/users/brunokrebs/orgs",
                   "repos_url": "https://api.github.com/users/brunokrebs/repos",
                   "events_url": "https://api.github.com/users/brunokrebs/events{/privacy}",
                   "received_events_url": "https://api.github.com/users/brunokrebs/received_events",
                   "type": "User",
                   "site_admin": false,
                   "name": "Bruno Krebs",
                   "company": null,
                   "blog": "http://www.brunokrebs.com",
                   "location": "Porto Alegre, RS - Brazil",
                   "email": null,
                   "hireable": null,
                   "bio": null,
                   "public_repos": 214,
                   "public_gists": 87,
                   "followers": 66,
                   "following": 0,
                   "created_at": "2015-10-27T17:00:09Z",
                   "updated_at": "2019-05-31T22:33:44Z"
                 }       
       ];
}
